### ISSUE TITLE
ModuleNotFoundError: No module named 'twint'

### ISSUE THREAD

**Issue by malashhab** [MrTuxx/SocialPwned#11]
whenever i run this command 
python3 socialpwned.py --credentials credentials.json --instagram --target-ig mhd_alashhab --followers-ig --followings-ig --pwndb

i get his error 

Traceback (most recent call last):
  File "/home/kali/SocialPwned/socialpwned.py", line 4, in <module>
    from core.main import run
  File "/home/kali/SocialPwned/core/main.py", line 10, in <module>
    from core import twitter
  File "/home/kali/SocialPwned/core/twitter.py", line 5, in <module>
    from lib.TwitterAPI import Twitter
  File "/home/kali/SocialPwned/lib/TwitterAPI/Twitter.py", line 4, in <module>
    import twint
ModuleNotFoundError: No module named 'twint'

**Comment by montserratguerrero** [comment]
Traceback (most recent call last):
  File "/home/kali/SocialPwned/socialpwned.py", line 56, in <module>
    run(args)
  File "/home/kali/SocialPwned/core/main.py", line 244, in run
    results.extend(twitterParameters(args,out_dir))
  File "/home/kali/SocialPwned/core/main.py", line 160, in twitterParameters
    users = twitter.getFollowers(args.target_tw,args.limit)
  File "/home/kali/SocialPwned/core/twitter.py", line 37, in getFollowers
    return Twitter.getFollowers(username,limit)
  File "/home/kali/SocialPwned/lib/TwitterAPI/Twitter.py", line 72, in getFollowers
    twint.run.Followers(c)
  File "/home/kali/.local/lib/python3.10/site-packages/twint/run.py", line 351, in Followers
    run(config)
  File "/home/kali/.local/lib/python3.10/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kali/.local/lib/python3.10/site-packages/twint/run.py", line 235, in main
    await task
  File "/home/kali/.local/lib/python3.10/site-packages/twint/run.py", line 253, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = username

me da este error al ejecutar el comando
python3 socialpwned.py --credentials credentials.json --twitter --target-tw username --all-tw --pwndb
