### ISSUE TITLE
ImportError: No module named requests_toolbelt

### ISSUE THREAD

**Issue by Popzindawood** [MrTuxx/SocialPwned#12]
Hi,

I got this issue when I launch : **python socialpwned.py** 

Traceback (most recent call last):
  File "socialpwned.py", line 4, in <module>
    from core.main import run
  File "/home/blakibali/Bureau/SocialPwned/core/main.py", line 4, in <module>
    from lib.InstagramAPI import InstagramAPI
  File "/home/blakibali/Bureau/SocialPwned/lib/InstagramAPI/__init__.py", line 1, in <module>
    from .InstagramAPI import *
  File "/home/blakibali/Bureau/SocialPwned/lib/InstagramAPI/InstagramAPI.py", line 18, in <module>
    from requests_toolbelt import MultipartEncoder
ImportError: No module named requests_toolbelt

So the application doesn't work du to this message. 

Hope u answer me

Regards,

**Comment by MrTuxx** [comment]
Try this:

`pip3 install requests_toolbelt`

**Comment by Popzindawood** [comment]
Ok i try with python3 and return it to me as twint.
So I did what u said in the twint topic and it works.

Thanks you
