### ISSUE TITLE
Error with twint despite already running commands

### ISSUE THREAD

**Issue by Aygx12** [MrTuxx/SocialPwned#15]
I have tried all the troubleshooting for twint, using the commands listed, but without success. I keep getting this errror: `Traceback (most recent call last):
  File "/home/kali/Desktop/osint/SocialPwned/socialpwned.py", line 4, in <module>
    from core.main import run
  File "/home/kali/Desktop/osint/SocialPwned/core/main.py", line 10, in <module>
    from core import twitter
  File "/home/kali/Desktop/osint/SocialPwned/core/twitter.py", line 5, in <module>
    from lib.TwitterAPI import Twitter
  File "/home/kali/Desktop/osint/SocialPwned/lib/TwitterAPI/Twitter.py", line 4, in <module>
    import twint
  File "/root/.local/lib/python3.9/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/root/.local/lib/python3.9/site-packages/twint/get.py", line 6, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str` How can I fix? Help pls

**Comment by MrTuxx** [comment]
hello,

can you specify which command you have executed?
