### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by Zachyie** [MrTuxx/SocialPwned#19]
Traceback (most recent call last):
  File "Downloads\PortableGit\SocialPwned\SocialPwned.py", line 8, in <module>
    banner.banner()
  File "Downloads\PortableGit\SocialPwned\core\banner.py", line 41, in banner
    centered = line.center(os.get_terminal_size().columns)
OSError: [WinError 6] The handle is invalid

**Comment by MrTuxx** [comment]
Run it on Linux or use Docker
